In [2]:
#import tensor
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
#create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [5]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
vector.ndim

1

In [9]:
matrix=tf.constant([[10,10,10],
                  [10,10,10],
                  [10,10,10]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [12]:
another_matrix=tf.constant([[[1,2,3],
                             [4,5,6]],
                            [[1,2,3],
                             [4,5,6]],
                            [[1,2,3],
                             [1,2,3]]])
another_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [13]:
another_matrix.ndim

3

In [ ]:
#what we have created till now?
# scalar :single number 
#vcetor :a number with direction(e.g:wind speed and direction)
#matrix:a 2-dimensional array of numbers
#tensor an n- dimensional array of numbers (where n can be any number ,a 0 dimensional tensor is a scalar , a 1 dimensional tensor is a vector)

In [4]:
#variable
tf.Variable


tensorflow.python.ops.variables.Variable

In [9]:
#random tensors with tensorflow
#random temsors are some arbitary sze and  which contain random numbers
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(5,2))
random_1

random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(5,2))
random_2

random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
#shuffle a tensor(valuable for when you want to shuffle your data in inherent)

variable=tf.constant([[1,2],
             [2,3],
             [4,5]])
variable
#shuffle our date
tf.random.shuffle(variable,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [1, 2],
       [4, 5]], dtype=int32)>

In [13]:
variable

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [4, 5]], dtype=int32)>

In [20]:
variable=tf.constant([[1,2],
             [2,3],
             [4,5]])
variable
#shuffle our date
#seting global seed and operational seed 
#and mainly shuffle is used for shuffling data and it 
#tf.random.shuffle(value, seed=None, name=None)
#is used as command.and when global seed  and operational seed is mentioned the data will not be shuffled
tf.random.set_seed(42)
tf.random.shuffle(variable,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
###if we want our shuffled tensors to be in the same order ,we have to use our global level random as well as operational seed


In [26]:
#create tensors of ones
tf.ones([3,5],tf.int32)


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [25]:
#create the tensors of zeros
tf.zeros([3,2],tf.int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [29]:
#converting numpy array to tensors
#theb main differnce between numpy array and tensor flow arrays is tensors can be run on GPU for faster mathematical computing
import numpy as np
numpy_a=np.arange(1,25,dtype=np.int32)
numpy_a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [36]:
#shape should be  equal to number of elements
#if not error will be thrown out
A=tf.constant(numpy_a,shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [35]:
B=tf.constant(numpy_a)
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [37]:
A.ndim

2